// all action types here

// to fet machines from server
export const FETCH_MACHINES = 'FETCH_MACHINES';
export const FETCH_MACHINES_START = 'FETCH_MACHINES_START';
export const FETCH_MACHINES_SUCCESS = 'FETCH_MACHINES_SUCCESS';
export const FETCH_MACHINES_FAIL = 'FETCH_MACHINES_FAIL';
// to sort and filter machines
export const SORT_MACHINES = 'SORT_MACHINES';
export const FILTER_MACHINES = 'FILTER_MACHINES';
// to update url
export const SORT_MACHINES_UPDATE_URL = 'SORT_MACHINES_UPDATE_URL';
export const FILTER_MACHINES_UPDATE_URL = 'FILTER_MACHINES_UPDATE_URL';
// for machine details
export const FETCH_MACHINE_DETAIL = 'FETCH_MACHINE_DETAIL';
export const FETCH_MACHINE_DETAIL_START = 'FETCH_MACHINE_DETAIL_START';
export const FETCH_MACHINE_DETAIL_SUCCESS = 'FETCH_MACHINE_DETAIL_SUCCESS';
export const FETCH_MACHINE_DETAIL_FAIL = 'FETCH_MACHINE_DETAIL_FAIL';
// to fetch live events
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_START = 'FETCH_EVENTS_START';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';
export const ADD_NEW_EVENT = 'ADD_NEW_EVENT';